version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=taskManagerDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grespost
      
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080